# Generated by Django 5.0.6 on 2024-07-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.IntegerField(null=True),
        ),
    ]
